import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, Mail } from "lucide-react";
import Image from "next/image";

const ProductDesc = () => {
  return (
    <div className="mx-auto p-20">
      <Carousel
        opts={{
          align: "start",
        }}
        className="w-full max-w-4xl m-auto"
      >
        <CarouselContent>
          <CarouselItem className="md:basis-1/2 lg:basis-1/3">
            <Card>
              <Image
                className="object-cover"
                width={1000}
                height={1000}
                src="/silica/img1.jpeg"
                alt="Silica Gel and Desiccants"
              ></Image>
            </Card>
          </CarouselItem>
          <CarouselItem className="md:basis-1/2 lg:basis-1/3">
            <Card>
              <Image
                className="object-cover"
                width={1000}
                height={1000}
                src="/silica/img2.jpg"
                alt="Silica Gel and Desiccants"
              ></Image>
            </Card>
          </CarouselItem>
          <CarouselItem className="md:basis-1/2 lg:basis-1/3">
            <Card>
              <Image
                className="object-cover"
                width={1000}
                height={1000}
                src="/silica/img4.jpeg"
                alt="Silica Gel and Desiccants"
              ></Image>
            </Card>
          </CarouselItem>
          <CarouselItem className="md:basis-1/2 lg:basis-1/3">
            <Card>
              <Image
                className="object-cover"
                width={1000}
                height={1000}
                src="/silica/img3.jpeg"
                alt="Silica Gel and Desiccants"
              ></Image>
            </Card>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>

      <div className="mt-10">
        <div className="my-4 flex gap-4 justify-between items-center flex-wrap">
          <h1 className="text-4xl font-bold underline ">
            Silica Gel and Desiccants
          </h1>
          <div className="flex flex-wrap gap-4 ">
            <Button onClick="/brosher.pdf" className="bg-blue-600">
              {" "}
              <Download className="mr-2" /> Download Brochure
            </Button>
            <Button className="bg-blue-600">
              <Mail className="mr-2" /> Request for MSDS
            </Button>
          </div>
        </div>

        <div className="mt-8">
          {" "}
          <div className="max-w-7xl mx-auto">
            {" "}
            <p className="text-gray-600 mb-6">
              GMD Silica gel effectively captures water molecules through the
              process of adsorption. This occurs as water atoms bond to the
              surface of the silica gel, forming a thin film until the entire
              surface is coated. Composed of an amorphous form of silica, GMD
              Silica gel boasts high porosity, featuring an interconnected
              network of microscopic pores (capillaries) that provide an
              expansive surface area. Moisture adsorption mechanisms include
              both surface adsorption and capillary condensation within this
              porous network.
            </p>{" "}
            <div className="mb-6">
              {" "}
              <h3 className="text-2xl font-bold text-gray-800 mb-4">
                Advantages
              </h3>{" "}
              <ul className="list-disc pl-6 text-gray-600">
                {" "}
                <li>
                  Non-flammable & Non-toxic: Ensures safety and peace of mind.
                </li>{" "}
                <li>
                  Extended Shelf Life: Up to 24 months when stored airtight.
                </li>{" "}
                <li>Inert Nature: Does not corrode or disrupt materials.</li>{" "}
                <li>
                  Prevents Fungus Growth: Maintains product integrity and
                  quality.
                </li>{" "}
                <li>
                  Food Grade Safe: Suitable for use in food-related
                  applications.
                </li>{" "}
                <li>
                  Maintains Crispiness: Ideal for preserving texture in food
                  products.
                </li>{" "}
                <li>
                  Reusable: Can be regenerated by heating to stave off
                  absorptions.
                </li>{" "}
                <li>
                  High Absorption Capacity: Can absorb up to 40% of its own
                  weight.
                </li>{" "}
              </ul>{" "}
            </div>{" "}
            <p className="text-gray-600 mb-6">
              Due to its non-toxic, odorless, and non-corrosive properties, GMD
              Silica Gel offers premium moisture control solutions with lower
              energy costs. It exhibits stable thermal and chemical
              characteristics, making it a reliable choice. Available in white,
              orange, and blue varieties, non-indicating types of silica gel
              remain physically unchanged even after moisture absorption.
            </p>{" "}
            <div className="mb-6">
              {" "}
              <h3 className="text-2xl font-bold text-gray-800 mb-4">
                Available Sizes
              </h3>{" "}
              <p className="text-gray-600">
                Ranges from 1 gram to 1000 grams packs, catering to various
                needs and applications.
              </p>{" "}
            </div>{" "}
            <div className="mb-6">
              {" "}
              <h3 className="text-2xl font-bold text-gray-800 mb-4">
                Applications
              </h3>{" "}
              <ul className="list-disc pl-6 text-gray-600">
                {" "}
                <li>Transformer and Electronics Industries</li>{" "}
                <li>Seed and Flower Drying</li>{" "}
                <li>Desiccant Pouch Manufacturing</li>{" "}
                <li>Aerospace & Aviation Industries</li>{" "}
                <li>Automobile Industries</li> <li>Power Industries</li>{" "}
              </ul>{" "}
            </div>{" "}
            <div className="mb-6">
              {" "}
              <h3 className="text-2xl font-bold text-gray-800 mb-4">
                Desiccants
              </h3>{" "}
              <p className="text-gray-600 mb-4">
                Desiccants play a crucial role in maintaining product stability
                by absorbing moisture from sealed containers, either through
                physical adsorption or chemical reactions. GMD offers specially
                designed clay-based desiccants that protect critical components
                from moisture damage.
              </p>{" "}
              <h4 className="text-xl font-bold text-gray-800 mb-2">
                Bentonite Clay Beads & Granules
              </h4>{" "}
              <ul className="list-disc pl-6 text-gray-600">
                {" "}
                <li>
                  Economical and cost-effective for engineering industries.
                </li>{" "}
                <li>
                  Effective even in extreme temperatures and humid environments.
                </li>{" "}
                <li>
                  Ideal for controlling moisture, humidity, and inhibiting mold,
                  mildew, corrosion, and odors.
                </li>{" "}
                <li>
                  Available in various packaging options for different
                  applications.
                </li>{" "}
                <li>
                  Easy to regenerate and does not swell upon adsorbing moisture.
                </li>{" "}
              </ul>{" "}
              <h4 className="text-xl font-bold text-gray-800 mt-4 mb-2">
                Advantages
              </h4>{" "}
              <ul className="list-disc pl-6 text-gray-600">
                {" "}
                <li>Natural and eco-friendly</li>{" "}
                <li>High adsorption capacity</li>{" "}
                <li>Safe for food and pharmaceuticals</li> <li>Easy to use</li>{" "}
              </ul>{" "}
            </div>{" "}
          </div>{" "}
        </div>
      </div>
    </div>
  );
};

export default ProductDesc;
